# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'py-file-guard-gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(430, 430)
        MainWindow.setMinimumSize(QtCore.QSize(430, 430))
        MainWindow.setMaximumSize(QtCore.QSize(430, 430))
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.txtLog = QtWidgets.QTextBrowser(self.centralwidget)
        self.txtLog.setGeometry(QtCore.QRect(10, 10, 410, 192))
        self.txtLog.setObjectName("txtLog")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 283, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setItalic(False)
        self.label.setFont(font)
        self.label.setToolTip("")
        self.label.setObjectName("label")
        self.modeBox = QtWidgets.QComboBox(self.centralwidget)
        self.modeBox.setGeometry(QtCore.QRect(10, 220, 130, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.modeBox.setFont(font)
        self.modeBox.setObjectName("modeBox")
        self.modeBox.addItem("")
        self.modeBox.addItem("")
        self.btnSelectFile = QtWidgets.QPushButton(self.centralwidget)
        self.btnSelectFile.setGeometry(QtCore.QRect(150, 220, 130, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btnSelectFile.setFont(font)
        self.btnSelectFile.setObjectName("btnSelectFile")
        self.inputKey = QtWidgets.QLineEdit(self.centralwidget)
        self.inputKey.setGeometry(QtCore.QRect(10, 308, 410, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.inputKey.setFont(font)
        self.inputKey.setObjectName("inputKey")
        self.btnSelectFolder = QtWidgets.QPushButton(self.centralwidget)
        self.btnSelectFolder.setGeometry(QtCore.QRect(290, 220, 130, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setItalic(False)
        self.btnSelectFolder.setFont(font)
        self.btnSelectFolder.setObjectName("btnSelectFolder")
        self.btnEncDec = QtWidgets.QPushButton(self.centralwidget)
        self.btnEncDec.setGeometry(QtCore.QRect(10, 374, 410, 40))
        self.btnEncDec.setObjectName("btnEncDec")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Py-File-Guard-GUI"))
        self.label.setText(_translate("MainWindow", "Your Key:"))
        self.modeBox.setToolTip(_translate("MainWindow", "Select Mode(Encrypt Or Decrypt)"))
        self.modeBox.setItemText(0, _translate("MainWindow", "Encrypt"))
        self.modeBox.setItemText(1, _translate("MainWindow", "Decrypt"))
        self.btnSelectFile.setToolTip(_translate("MainWindow", "Select Files For Encrypt/Decrypt"))
        self.btnSelectFile.setText(_translate("MainWindow", "Select Files"))
        self.inputKey.setToolTip(_translate("MainWindow", "Enter Your  Password"))
        self.btnSelectFolder.setToolTip(_translate("MainWindow", "Select Output Folder For Save Files"))
        self.btnSelectFolder.setText(_translate("MainWindow", "Select Folder"))
        self.btnEncDec.setText(_translate("MainWindow", "Encrypt"))
